### PR TITLE
Validate hidden fields

### PR DESCRIPTION
**Pull request by Firesphere**
Validate SecurityID and AuthenticationMethod to prevent errors by tampering with the form

### CODE REVIEW

**Comment by Firesphere** [comment]
Scrutinizer is actually finished

**Comment by robbieaverill** [comment]
This looks like it has some crossover with #38?

**Comment by Firesphere** [comment]
@robbieaverill  Yes, I made sequential PR's so they could be more easily recognized as what part of the work was done

**Comment by ScopeyNZ** [comment]
Merged in #38 (after a rebase)

**Pull request closed without merging**
